title = "fib"
description = "Calculate fibs"
version = "0.1.0"
license = "Apache-2.0"
authors = [ "Pouya Eghbali <pouya.eghbali@yandex.com>" ]
keywords = ""

[build]
source = "src"
destination = "build"
target = "js"

[scripts]
test = "No tests specified"

[dependencies]
stdlib = "latest"

[[servers]]
proto = "wt"
name = "default"

[[workers]]
proto = "wt"
count = "cpu"
server = "default"

[executor]
proto = "wt"
wait_for = "cpu"
server = "default"

# Npm specific configs

[npm.scripts]
start = "node .clio/index.js"
host = "node .clio/host.js"
